name: Build LaTeX PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile LaTeX document
      run: |
        cd CV
        latexmk -pdf main.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: CV/main.pdf
